- name: Playbook to configure IPA clients with username/password
  hosts: ipaclients

  roles:
  - role: redhat.rhel_system_roles.network
    state: present 

  - role: redhat.rhel_idm.ipaclient
    state: present
